version: '3.7'

services:
    wheel-of-luck-client:
        build: .
        image: wheel-of-luck-client:latest
        container_name: wheel-of-luck-client
        networks:
            - saba
        logging:
            driver: 'json-file'
            options:
                max-size: '100m'
                max-file: '10'
        restart: unless-stopped

networks:
    saba:
        external:
            name: saba
